name: Verify

on: [push]

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install deps
        run: npm install

      - name: Install CLIHub
        run: npx --yes clihub@latest install verified-agent-identity

      - name: Create Identity
        run: node scripts/createNewIdentity.js

      - name: Link Identity
        run: node scripts/humanLinkHumanToAgent.js --challenge '{"name":"keso1234"}'
